# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5e864c2bddc8c7d9107dbfa94abec71e5b25a29f80a222348a84c51c3f796f2e36fe3eae82a6cc86c21a8987a4acb5f5c4d3613a633fdaa67a071c2f67ac8f53

test:
  secret_key_base: b215254cf29b972f18fc524870721415c941d0340d24ca3a9dc2b6eecd11a6cbb92a5b82d119ad7780619ff56b8bb7b1b4d0c7ddafb5c6f4815fd657f280594b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
